PHOTOX/promdens

IC_filtering.py

Just small stylistic fixes pointed out by ruff linter. Looks pretty clean otherwise!

Fixes from ruff linter

---

promdens.py

We can use `argparse` (using the [choices parameter](https://docs.python.org/3/library/argparse.html#choices) to handle checking the user input (e.g. energy units).

Handle input choices in argparse parser

---

README.md
promdens.py

I copied the text from the manuscript into README.md and slightly modified. The description will get better in the next release.

One small modification in promdens.py and more details in README.md

---

promdens.py

Minor refactor. I think it makes more sense to convert units automatically right after the data are read in. That way programmer cannot screw this up and we can delete a bunch of checks.
Marking as draft, we'll merge after release.

Convert units in read_input_data

---

promdens.py

Moving plotting into separate functions, towards #2.
Might be hard to review in on Github, probably better to open locally. But I just literally moved the code into functions and adjusted some print statements.

Move plotting into functions

---

.github/workflows/ci.yml
README.md
promdens.py

This is a last PR that mostly just moves code. Now that all the code is out of global scope, we can make this into an importable module / package in next PR. 
This also exposed a couple of cases in `sample_initial_conditions()` method which relied on global variables.
Closes #2

Move code to `main()`

---

src/promdens/promdens.py

Extracted from #14 
- group options in argparse parser
- move matplotlib import to plot functions

Group CLI options

---

src/promdens/promdens.py

Last PR today. Extracted from #14. Unlike in that PR, here I don't (yet) touch any of the actual code in the `InitialConditions` class, apart from some print statements so this should be a fairly safe change.

Add LaserPulse dataclass

---

.github/workflows/ci.yml
.gitignore
pyproject.toml
src/promdens/promdens.py
tests/conftest.py
tests/test_pulse.py

The code change here is very simple, just moving the `field_cos` method to the LaserPulse class.
The more interesting thing are the new tests using the pytest framework. It can be quite weird at first, but at least reading the [quick guide doc](https://docs.pytest.org/en/stable/getting-started.html) might give some idea. Happy to answer any questions.

Move `field_cos` method to `LaserPulse` class, add unit tests

---

README.md
src/promdens/promdens.py

Adding latex style formulas for the analytic wigner transforms.

Improving Readmd with analytic formulas

---

.github/workflows/ci.yml
supplementary/envelopes_analysis/field_envelopes.py

Run field_envelopes.py script in CI

---

pyproject.toml
supplementary/envelopes_analysis/field_envelopes.py
tests/conftest.py
tests/test_methods_nai.py
tests/test_pulse.py

Just a small cleanup, extracted from #26 
Again marking as draft in order to not merge figure changes by accident.

Cleanup `field_envelopes.py`

---

.github/workflows/publish.yml

Publishing `promdens` package will be triggered by creating a tag starting with `v`.

CI workflow for publishing to PyPI

---

pyproject.toml

Links in project.toml

---

LICENSE
pyproject.toml

Let's go with the simplest and least restrictive option (we don't care about code being stolen, as long as they cite us properly! :smile: )
https://choosealicense.com/licenses/mit/

Add MIT LICENSE

---

README.md

@JanosJiri feel free to improve or expand this if something doesn't seem clear.

README: Recommend pipx|uv for installation

---

.github/workflows/publish.yml
pyproject.toml

See https://stackoverflow.com/a/62331521/3682277 for explanation
Closes #38
Also, we should document the release workflow, perhaps in `CONTRIBUTING.md`. Will do that once I get back.

Trigger release to TestPyPI by test-release PR label

---

CITATION.cff
README.md
pyproject.toml

I messed up the previous branch so I created a new one with the same changes.

Getting ready for release v1.0.0

---

.github/workflows/ci.yml

Python 3.13 has been released a couple days ago, let's test it!

CI: Test python 3.13

---

.github/workflows/ci.yml
.github/workflows/publish.yml
README.md

Adding a brief section on the testing suite showing it can be triggered by `pytest`.

Update README.md with testing info
